### ISSUE TITLE
Question [Auth]

### ISSUE THREAD

**Issue by austinGENEreeve** [wwdrew/expo-spotify-sdk#4]
Hey, have you been able to get this working? I'm getting an "Invalid Spotify configuration" when trying to authenticate with spotify

**Comment by wwdrew** [comment]
Hi, yes it definitely works - it's being successfully used in at least one commercial app.

Would love to help you out though, at which point are you getting that error?

**Comment by austinGENEreeve** [comment]
I get the error when clicking my auth button triggering this code: 
```  const session = await authenticateAsync({
        scopes: [
          "user-read-recently-played",
          "user-read-playback-state",
          "user-modify-playback-state",
          "user-library-read",
        ],
      });```
      
      ERROR:  "Invalid Spotify configuration"
      
      I've added the package and installed my pods.
      I also added this to my app.json
      ```
      expo: {
      ...
 "plugins": [
      "expo-router",
      [
        "@wwdrew/expo-spotify-sdk",
        {
          "host": "authenticate",
          "scheme": "myAppName",
          "clientID": "[myClientId]"
        }
      ]
    ],```

**Comment by wwdrew** [comment]
When you say you've installed your pods, do you mean you're just doing a `pod install` or are you running the `expo prebuild` command? This module uses a config plugin to set up your project with the correct configuration, so it's possible this might not be running.

Also, I'm assuming you've set up your Spotify app in the developer dashboard and that's the client id value you're using?

**Comment by austinGENEreeve** [comment]
I did my prebuild a second time and now it's working! Thanks for the feedback

**Comment by wwdrew** [comment]
Oh great stuff, glad to hear you got it working!
