### ISSUE TITLE
Error with the example

### ISSUE THREAD

**Issue by Stef-00012** [wwdrew/expo-spotify-sdk#8]
I tried cloning the repository and using the example but when i go to open the app with Expo Go i get
`Error: Cannot find native module 'ExpoSpotifySDK', js engine: hermes`

**Comment by kplynds** [comment]
Are you in Expo go? I could be wrong but I believe you need to be using a development build because the package uses native code. 
https://docs.expo.dev/workflow/customizing/#using-libraries-that-include-native-code

**Comment by wwdrew** [comment]
Yeah, sorry but this is a native module that requires using development builds, you can't run it in Expo Go.
